# YAML input file for Kalimotxo

mail: # specify emails and server
    to: ulisesrojo@cio.mx, sma@cio.mx, enrique@cio.mx
    from: medusa@cio.mx
    servidor: amorfo.cio.mx

sensor: # sensor parameters
    temp_nor: 20
    temp_cri: 32
    temp_dis: 38
    pin: 23
    frec: 10

log_file: /home/pi/proyectos/kalimotxo/temperature.log # path to output log
